### ISSUE TITLE
docker build failed with autogen not found

### ISSUE THREAD

**Issue by yhzhao** [discordianfish/docker-spotter#12]
Step 8 : RUN go get -d && go build
 ---> Running in 997d297f0f8f
package github.com/docker/docker/utils
	imports github.com/Sirupsen/logrus
	imports github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/local/go/src/pkg/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)
2015/03/31 19:33:38 The command [/bin/sh -c go get -d && go build] returned a non-zero code: 1

Has anyone able to modify the Dockerfile and build successfully?

Thanks.

**Comment by discordianfish** [comment]
Thanks for the report. This should be fixed by https://github.com/discordianfish/docker-spotter/commit/4704527bf413b0945c3599640c73db260caeb52d, feel free to reopen if not.
