### ISSUE TITLE
Can't build- problems with dependencies from docker/docker

### ISSUE THREAD

**Issue by yonah-codefresh** [discordianfish/docker-spotter#13]
I'm not experienced with Go but I've tried to get docker-spotter to build several ways and can't seem to get past the dependencies on docker/docker.

Using the Dockerfile I get the following error:
package github.com/docker/docker/pkg/jsonmessage
	imports github.com/dotcloud/docker/utils
	imports github.com/Sirupsen/logrus
	imports github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion
	imports github.com/docker/docker/autogen/dockerversion: cannot find package "github.com/docker/docker/autogen/dockerversion" in any of:
	/usr/lib/go/src/pkg/github.com/docker/docker/autogen/dockerversion (from $GOROOT)
	/go/src/github.com/docker/docker/autogen/dockerversion (from $GOPATH)

I managed to get past the dockerversion error following instructions here: https://github.com/docker/docker/issues/10922

Then I get a different error:
package github.com/docker/docker/pkg/jsonmessage: exit status 1
package github.com/docker/docker/pkg/stringid
	imports github.com/docker/docker/pkg/stringid
	imports github.com/docker/docker/pkg/stringid: cannot find package "github.com/docker/docker/pkg/stringid" in any of:
	/usr/lib/go/src/pkg/github.com/docker/docker/pkg/stringid (from $GOROOT)
	/root/gocode/src/github.com/docker/docker/pkg/stringid (from $GOPATH)

Would love to try docker-spotter. 
Thanks,
Yonah

**Comment by tuxflo** [comment]
I have exactly the same issue here!
I also tried to execute `.go-autogen` script from the *hack/make* folder as described [here](https://github.com/docker/docker/issues/10922) but still getting the same errors.

**Comment by medined** [comment]
I am seeing the same issues.

**Comment by discordianfish** [comment]
This should be fixed by #14. Feel free to reopen if it's not working for you.
